# Generated by Django 6.0 on 2025-12-04 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensores', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(choices=[('apertura manual', 'Apertura manual'), ('cierre manual', 'Cierre manual'), ('apertura automatica', 'Apertura automatica'), ('cierre automatico', 'Cierre automatico')], max_length=100)),
                ('estado', models.CharField(choices=[('permitido', 'Permitido'), ('denegado', 'Denegado')], max_length=10)),
                ('sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sensores.sensor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
    ]
